<div class="bgcolor7 padding-bottom-60 padding-top-20">

    <div class="container">
        <div class="row">
            <div class="col-sm-10 floatNone Centrato textCenter">
              
                      <br /> <br />

                        <img src="<?php echo $this->basePath('img/errore404.png') ?>" class="img-responsive Centrato" />
                        <br />
                        <h1 class="textLeft fw700 noMarginBottom">ERROR 404</h1>
<h2 class="fw400 textLeft lh50">You broke <strong>Zf2</strong>, congratz.</h2>
 
<p class="fs24 textLeft fw400 lh32">This page doesn't exist or some other horrible error occurred.
<br /><br />
But at DeRev this error can't be ignored, and someone has to be fired! <br />
Contribute to a crowdfunding campaigns and let us know: you'll save a developer's life and we'll double your donation (withdrawing it from his salary!).</p>

                      <br /> <br />
                       <a href="/" class="btn btn-md btn-base textUppercase">BACK TO USER PROFILE</a><span class="hidden-xs">&nbsp; &nbsp;</span>
                       <a href="/" class="btn btn-md btn-base textUppercase">BACK TO HOMEPAGE</a>
                       <br /> <br />
            </div><!--end col-sm-6-->
        </div><!--end row-->
    </div><!--end container-->
</div><!--end bgcolor7-->                        
